name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    name: EAS Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./mobile-app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas/using-eas-cli-with-github-actions/#using-secrets-in-github-actions"
            exit 1
          fi

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm
          cache-dependency-path: ./mobile-app/package-lock.json

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Build on EAS
        run: eas build --platform android --profile preview --non-interactive
